#!/usr/bin/env bash
#
# create-release-keystore.sh — one-shot setup for the permanent
# Interact Pro release keystore.
#
# Background:
# Yesterday's APK was signed with the auto-generated debug keystore
# (~/.android/debug.keystore). Today's APK was also signed with the debug
# keystore, but the debug keystore had been regenerated (likely by an
# Android Studio update overnight). Result: existing installs see today's
# APK as "different app" → upgrade fails with INSTALL_FAILED_UPDATE_INCOMPATIBLE
# and Android shows the unhelpful "App not installed" dialog.
#
# Fix:
# Create ONE permanent keystore now, store it OUTSIDE the project (in
# ~/.keystores/ — not in the repo, not in build/ which gradle clean wipes),
# and reference it from android/key.properties (gitignored). Every future
# build is signed with this keystore. Upgrade-installs work indefinitely.
#
# Run this once. Re-running is a no-op if the keystore already exists.
#
# Usage:
#   bash scripts/create-release-keystore.sh
#
# After running, EVERY APK / AAB built via build-and-upload.sh will be
# signed with this keystore. Existing installs of the previously
# debug-signed APKs will still need a one-time uninstall — but no
# subsequent upgrade ever will.

set -euo pipefail

KEYSTORE_DIR="$HOME/.keystores"
KEYSTORE_FILE="$KEYSTORE_DIR/interact_pro_release.jks"
KEY_ALIAS="interact_pro"

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KEY_PROPERTIES="$PROJECT_DIR/android/key.properties"

mkdir -p "$KEYSTORE_DIR"
chmod 700 "$KEYSTORE_DIR"

if [ -f "$KEYSTORE_FILE" ]; then
  echo "✓ Release keystore already exists at $KEYSTORE_FILE"
else
  echo "Creating new release keystore at $KEYSTORE_FILE"
  echo
  echo "You will be prompted for:"
  echo "  • Keystore password (use something memorable, but not 'password')"
  echo "  • Key password (just press Enter to use the same as keystore password)"
  echo "  • Distinguished name fields (CN/OU/O/L/ST/C — defaults are fine)"
  echo
  echo "STORE THE KEYSTORE PASSWORD SOMEWHERE SAFE (1Password, Bitwarden,"
  echo "Apple Keychain). If you lose it, you can NEVER ship updates to"
  echo "this app again — every existing install becomes orphaned."
  echo

  keytool -genkey -v \
    -keystore "$KEYSTORE_FILE" \
    -keyalg RSA \
    -keysize 4096 \
    -validity 36500 \
    -alias "$KEY_ALIAS" \
    -storetype JKS \
    -dname "CN=Interact Pro, OU=Engineering, O=InteractPak, L=Karachi, ST=Sindh, C=PK"

  chmod 600 "$KEYSTORE_FILE"
  echo
  echo "✓ Keystore created at $KEYSTORE_FILE"
fi

# Prompt for the password we just used so we can write key.properties.
# Doing it as a separate prompt (not capturing keytool stdin) avoids
# round-tripping the password through bash variables visible in `ps`.
if [ ! -f "$KEY_PROPERTIES" ]; then
  echo
  echo "Now creating $KEY_PROPERTIES with the keystore reference."
  echo "Enter the keystore password you just set (will not be echoed):"
  read -r -s STORE_PASS
  echo

  cat > "$KEY_PROPERTIES" <<EOF
# Auto-generated by scripts/create-release-keystore.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# This file is gitignored — keep it that way. The keystore itself lives at
# $KEYSTORE_FILE (also outside the repo).
storeFile=$KEYSTORE_FILE
storePassword=$STORE_PASS
keyAlias=$KEY_ALIAS
keyPassword=$STORE_PASS
EOF
  chmod 600 "$KEY_PROPERTIES"
  echo "✓ Wrote $KEY_PROPERTIES"
else
  echo
  echo "✓ $KEY_PROPERTIES already exists — leaving it alone."
  echo "  (If you regenerated the keystore, edit storePassword / keyPassword manually.)"
fi

echo
echo "─────────────────────────────────────────────────────────────"
echo "Verifying that build.gradle.kts will pick up the new keystore:"
grep -A 2 "keystoreProperties" "$PROJECT_DIR/android/app/build.gradle.kts" | head -8
echo "─────────────────────────────────────────────────────────────"
echo
echo "Next step:"
echo "  bash scripts/build-and-upload.sh --android-only"
echo
echo "The first build with the new keystore signs the APK + AAB."
echo "Tell the Sony TV (and every other device with the previous APK)"
echo "to UNINSTALL the old version once before installing this build —"
echo "after that one uninstall, every future build upgrades cleanly forever."
